name: newline Workflow

on:
  workflow_dispatch:  # 手動実行可能

env:
  ENV_VARS: |
    [
      {
        "name": "ENV1",
        "value": "【test】Its test message!!\n\nescape test!\nand eof test!"
      },
      {
        "name": "TZ",
        "value": "Asia/Tokyo"
      }
    ]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "ENV_VARS: $ENV_VARS"
          ENV_VARS_ARG="--set-env-vars"

          ENV_COUNT=$(echo "$ENV_VARS" | jq '. | length')
          echo "ENV_COUNT: $ENV_COUNT"

          for ((i=0; i<$ENV_COUNT; i++)); do
            ENV_NAME=$(echo "$ENV_VARS" | jq -r ".[$i].name")
            ENV_VALUE=$(echo "$ENV_VARS" | jq -r ".[$i].value")

            if [[ "$ENV_VALUE" == *$'\n'* ]]; then
              ENV_VALUE=$(echo "$ENV_VALUE" | sed ':a;N;$!ba;s/\n/\\n/g')
              ENV_VARS_ARG="$ENV_VARS_ARG $ENV_NAME=\$'$ENV_VALUE'"
            else
              ENV_VARS_ARG="$ENV_VARS_ARG $ENV_NAME=$ENV_VALUE"
            fi
          done

          echo "ENV_VARS_ARG: $ENV_VARS_ARG"
